version: '3'

services:

    jekyll:
        image: jekyll/jekyll:latest
        command: jekyll serve --watch --incremental --drafts
        ports:
            - 4000:4000
        environment:
            JEKYLL_ENV: development
            FORCE_POLLING: "true"
        volumes:
            - .:/srv/jekyll
